#!/bin/bash

files="${@}"

[ -z "$files" ] &&
  echo "usage: $(basename $0) <files>" &&
  exit

tmpdir="/tmp/bashball-$$/"
mkdir -p "$tmpdir"
trap 'rm -rf $tmpdir' EXIT

cat << 'EOF' > "$tmpdir/ball"
#!/bin/bash
export _localdir="$( cd "$( dirname $0 )" && pwd )"; export _tmpfolder="/tmp/bashball-$$"; source() { path="$1"; if [[ "$path" =~ ^[a-zA-Z0-9] ]] ; then . "$_tmpfolder/$path"; else [[ "$path" == ..* ]] && cd $_tmpdir; . $path; fi; cd $_launchdir; }; export -f source; trap "rm -rf $_tmpfolder" EXIT; mkdir -p $_tmpfolder; printf $'
__TAR
' | base64 -d | tar xz -C $_tmpfolder; bash $_tmpfolder/main.sh "${@}"
EOF

tar -czf - $files | base64 -w0 > "$tmpdir/tar"

printf '%s\n' "/__TAR/r $tmpdir/tar" w | ed "$tmpdir/ball" 1>/dev/null 2>&1

cat "$tmpdir/ball" | tr '\n' '\r' | sed 's/\r__TAR\r//' | sed 's/=\r/=/' | tr '\r' '\n'
